### ISSUE TITLE
Add Integration tests for saving instance state

### ISSUE THREAD

**Issue by maltzj** [mattlogan/Pancakes#10]
Although the unit test coverage is good, we should probably have a couple of integration tests to ensure that something like #8 doesn't accidentally cause breakage in a real app.

**Comment by mattlogan** [comment]
@maltzj I migrated the JVM test to be an Android instrumentation test that runs on a device. This way, we're using real Bundles and ViewGroups.

I haven't written a test to repro the ClassCastException crash, but now that that's fixed I don't think we need that in there.

Are there any other use cases that you can think that aren't covered in the existing tests?
