### ISSUE TITLE
Add some sort of hook to tell users of ViewStack that a view has been inflated

### ISSUE THREAD

**Issue by maltzj** [mattlogan/Pancakes#11]
`OnStackChangedListener` is nice for knowing when things have been added to a `ViewStack`, but oftentimes you'll want to know when your view has been inflated and ready for use (i.e. hooking up Presenters).  

The sample app accomplishes this by hooking into a `View`'s `onFinishInflate` method, but that feels like leaking implementation details to the view.

If we decide to do thise, we can probably do it by hooking into the `OnFirstLayoutListener` that's already being used in the `ViewStack`

**Comment by mattlogan** [comment]
What do you think about adding a few callbacks? Maybe something equivalent to onDestroy?

I was initially thinking of letting the View handle all this lifecycle stuff through its own callbacks -- onFinishInflate, onAttached, onDetached etc. Do you think it's worth having a separate interface with two or more "lifecycle" callbacks?

**Comment by mattlogan** [comment]
@maltzj I'm actually leaning against this for now. I don't think using `onFinishInflate` is a bad thing at all, and I actually wanted to let the View lifecycle be the only real lifecycle component of this library.

Doing View setup in `onFinishInflate` is actually a pretty common practice I think (see u2020: https://github.com/JakeWharton/u2020/blob/52e842ae54e80c8a91f5ec317e7319caadf80a21/src/main/java/com/jakewharton/u2020/ui/trending/TrendingItemView.java#L42).

The only reason I'd see a need for an extra callback is if you wanted to know when the View was inflated from outside of the View itself, like in the hosting Activity for example.

Let me know what you think.

**Comment by mattlogan** [comment]
Added in 4.0.0
