### ISSUE TITLE
Add StackChangedListener

### ISSUE THREAD

**Issue by mattlogan** [mattlogan/Pancakes#2]
This is in response to the previously closed pull request https://github.com/mattlogan/Pancakes/pull/1.

I think it is useful to have a StackChangedListener so consumers can be notified of changes to the navigation stack. This may useful for situations like updating the host Activity's Toolbar with data provided by a View. For example:

```java
public class DogsView implements NamedView {
    // ...

    @Override
    public String viewName() {
        return "Dogs";
    }
}
```

Then in the host Activity:

```java
public class DogActivity extends AppCompatActivity {
    // ...

    @Override
    public void onStackChanged() {
        NamedView topView = (NamedView) viewStack.peekView();
        toolbar.setTitle(topView.viewName());
    }
}
```

**Comment by mattlogan** [comment]
Added commit https://github.com/mattlogan/Pancakes/commit/2a1d677da90b24a0423c9ec5ffc01c6b6cf94ec0

The tricky part is knowing when to notify the listeners, especially in the case of an animation. I settled on notifying after BOTH the ViewStack's size AND the top View in the ViewGroup container have changed. For a push with an animation, this happens before the animation starts (right after the new View is added to the container). For a pop with an animation, this happens after the animation completes (right after the old view is removed from the container).

Feedback is welcome. I'll think about this a bit more before writing some tests and preparing a release.

**Comment by matthewrice345** [comment]
Thanks for considering adding the listener. What you posted above is basically what I ended up doing in Volume Butler. I just converted most of the app over to views using Pancakes. Seems to be pretty solid way to make sure things display correctly.

**Comment by mattlogan** [comment]
Awesome! Yeah, I'm not sure I'd use the listener in my own app. I think I prefer calling stuff on the Activity from the Views in onFinishInflate(). But it's a valid use case nonetheless, and I think it's worth supporting!

**Comment by mattlogan** [comment]
For anyone looking at this in the future, there is now a StackChangedListener as of 3.1.0.

https://github.com/mattlogan/Pancakes/commit/2a1d677da90b24a0423c9ec5ffc01c6b6cf94ec0
