### ISSUE TITLE
How do you pass data between views?

### ISSUE THREAD

**Issue by rubixhacker** [mattlogan/Pancakes#3]
What mechanism do you propose to pass data between views when using Pancakes since the view does not get a Bundle and the view is getting created in xml?

**Comment by mattlogan** [comment]
I imagine that I'd create a ViewFactory with whatever values or dependencies the view needs, then pass that stuff onto the view in the `createView` method. ViewFactories get serialized, so any fields in the ViewFactory should be Serializable. Bundles could work well here, but any Serializable type would be fine. That would look something like this:

```java
public class DogViewFactory implements ViewFactory {

    private final Bundle dogs;    

    public DogViewFactory(Bundle dogs) {
        this.dogs = dogs;
    }

    @Override
    public View createView(Context context, ViewGroup container) {
        DogView dogView = LayoutInflater.from(context).inflate(R.layout.view_dog, container, false);
        dogView.initWithDogs(dogs);
        return dogView;
    }
}
```

```java
viewStack.push(new DogViewFactory(dogs));
```
