### ISSUE TITLE
Why is this not a being developed to replace flow and mortar?

### ISSUE THREAD

**Issue by frostymarvelous** [mattlogan/Pancakes#6]
I see so much potential for this library.
You already create a factory for each view right?
Why not go the extra step and add lifecycle methods (borrow from react) to each factory (probably rename it as something else) and in so doing replace both fragments and the clunky implementation that flow and mortar is.

Seriously this is really good and I've been thinking of doing something like this,
I've forked the lib so if you are not interested in going that far, I'm going to go ahead and make it just that.

**Comment by frostymarvelous** [comment]
To demonstrate what I said above, I've made a completely different library here based on your code.
https://github.com/frostymarvelous/Folio


There are some patches you might be interested in. Like a uniform push, pop API (renamed as goTo and goBack in this instance) and passing the exit animation so that when the back button is clicked, the exit is animated.

**Comment by mattlogan** [comment]
I appreciate the enthusiasm but I'm not really interested in adding a whole lot more functionality to this library. It's really only intended to act as a navigation stack for Views -- not anything to with lifecycle or presenters etc.

**Comment by frostymarvelous** [comment]
That's cool. I actually have gone very far with my library. Hopefully, I should be done quite soon. Maybe then, you'd be interested in testing it out.

**Comment by mattlogan** [comment]
Sure!
