### ISSUE TITLE
Is there a way to manage a dual-pane mode?

### ISSUE THREAD

**Issue by RoRoche** [mattlogan/Pancakes#7]
Is it possible to manage a master/detail application using the `ViewStack` class?

Where the `ViewStack` class would 

* route to the detail screen in single-pane mode,
* or push the `DetailView` to its dedicated container next to the `MasterView` in dual-pane mode.

**Comment by mattlogan** [comment]
Hey there, sorry for the late reply.

I didn't consider two panes at all here, mostly because there are so many possible flows and use cases for two pane mode. Lemme know if you get something working and we can update the docs and/or add to the sample app.
