### ISSUE TITLE
ViewStack.readFromBundle crashes with a ClassCastException.

### ISSUE THREAD

**Issue by maltzj** [mattlogan/Pancakes#8]
When you call `viewStack.readFromBundle`, it raises a ClassCastException with a message `java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Stack`

This is related to https://code.google.com/p/android/issues/detail?id=3847.

Matt and I discussed in Slack and we think the best way to handle this is to just store view resource ids within `ViewStack` and then parcel/unparcel them using parcelable.

**Comment by mattlogan** [comment]
Related suggestion from a while ago: https://github.com/mattlogan/Pancakes/issues/5

**Comment by mattlogan** [comment]
Fixed
